'use client';
import {useState} from 'react';

const O={
 genre:['Mandarin Emotional Pop-Rock','Mandarin Pop Ballad','Cinematic Pop','Adult Contemporary','R&B Pop','Indie Pop','Folk Pop','Soft Rock'],
 mood:['Melancholic','Yearning','Regretful','Nostalgic','Bittersweet','Hopeful','Lonely','Restrained','Desperate','Cathartic'],
 tone:['Warm','Dark','Deep','Husky','Raspy','Breathy','Clean','Gritty','Smoky','Resonant'],
 technique:['Conversational phrasing','Chest-dominant mix','Controlled rasp','Sustained upper notes','Subtle vibrato','Falsetto contrast','Soft onset','Powerful belt'],
 groove:['Steady 4/4','Half-time emotional groove','Driving live-rock groove','Sparse ballad pulse','Syncopated pop groove'],
 melody:['Narrow conversational verse','Rising pre-chorus contour','Wide chorus range','Strong recurring hook','Long sustained chorus notes','Simple memorable motif','Call-and-response phrases'],
 harmony:['Minor-key leaning','Bittersweet major/minor mixture','Simple diatonic harmony','Tension-building pre-chorus','Emotional suspended chords','Dramatic borrowed chords'],
 instruments:['Piano','Acoustic Guitar','Clean Electric Guitar','Distorted Electric Guitar','Live Drums','Bass','Cinematic Strings','Atmospheric Pads','Backing Vocals','Percussion'],
 production:['Vocal-forward mix','Warm low-midrange','Spacious stereo image','Controlled plate reverb','Short vocal delay','Natural dynamics','Organic live feel','Modern polished master'],
 avoid:['EDM drops','Trap hi-hats','Excessive vocal runs','Constant belting','Bright synth leads','Overly theatrical singing','Over-compression','Busy arrangement','Early climax']
};
const sections=['Verse 1','Pre-Chorus','Chorus 1','Verse 2','Chorus 2','Bridge','Final Chorus'];
const hookTypes=[['Short repeated phrase','短句重复型','用简短、易重复的短句建立记忆点。'],['Melodic hook','旋律型 Hook','用容易哼唱的核心旋律成为歌曲标志。'],['Question / answer hook','问答型 Hook','由主唱提出问题，再用回应形成互动。'],['Emotional declaration','情绪宣告型','用直接而有力度的情绪句表达核心真相。'],['Title-centered hook','标题中心型','让歌名成为副歌最重要的记忆锚点。'],['Rising hook','上扬型 Hook','让 Hook 的音高或情绪逐步上扬。'],['Call-and-response','呼应型 Hook','主唱与和声或伴唱形成呼应。']];
const hookRepetition=[['Low','低'],['Moderate','中等'],['Strong','强'],['Very Strong','非常强']];
const hookPlacement=[['Pre-Chorus tease','Pre-Chorus 预告'],['Chorus opening','Chorus 开头'],['Chorus ending','Chorus 结尾'],['Both opening and ending','开头与结尾']];
const journeyOptions={verse:[['Intimate','亲密'],['Restrained','克制'],['Conversational','对话感'],['Breathier','更气声'],['Dark / controlled','深沉 / 控制']],pre:[['Increasing tension','张力增加'],['Rising register','音区上扬'],['More projection','更多投射'],['Controlled urgency','克制的紧迫感'],['Gradual opening','逐步打开']],chorus:[['Open and powerful','开放且有力量'],['Emotional release','情绪释放'],['Chest-dominant mix','胸声主导混声'],['Wider range','更宽音域'],['Strong sustained notes','强劲延长音']],bridge:[['Pull back','收回力度'],['Vulnerable','脆弱坦诚'],['Dramatic contrast','戏剧性对比'],['Near-spoken','接近说唱'],['Tension rebuild','重建张力']],final:[['Maximum emotional release','最大情绪释放'],['Strongest projection','最强投射'],['Added harmony layers','增加和声层'],['Selective ad-libs','选择性 Ad-libs'],['Highest safe register','安全范围内最高音区']]};
const help={Warm:'圆润饱满，高频更柔和。',Dark:'更低沉厚重，减少明亮感。',Husky:'带气息的沙哑感，亲密而成熟。',Raspy:'比 Husky 更明显的粗粝边缘。',Gritty:'在情绪高点加入可控的失真质感。',Breathy:'更多空气感，亲密而脆弱。','Chest-dominant mix':'保持胸声重量的高音区，不是纯粹喊唱。','Controlled rasp':'主要在情绪峰值增加纹理，不要全程使用。','Sustained upper notes':'延长重要副歌音符，制造抬升感。','Conversational phrasing':'主歌使用接近说话的自然节奏。'};
function Multi({items,value,setValue,max=99}){return <div className="chips">{items.map(item=>{const x=Array.isArray(item)?item[0]:item;return <button type="button" title={help[x]||''} key={x} className={value.includes(x)?'on':''} onClick={()=>setValue(value.includes(x)?value.filter(v=>v!==x):(value.length<max?[...value,x]:value))}>{Array.isArray(item)?<><b>{item[1]}</b><small>{item[2]}</small></>:<>{x}{help[x]&&<small>ⓘ</small>}</>}</button>})}</div>}
function Choice({items,value,setValue,multiple=false}){return <div className="choices">{items.map(item=>{const selected=multiple?value.includes(item[0]):value===item[0];return <button type="button" key={item[0]} className={selected?'on':''} onClick={()=>multiple?setValue(selected?value.filter(x=>x!==item[0]):[...value,item[0]]):setValue(item[0])}><b>{item[1]}</b><small>{item[2]||''}</small></button>})}</div>}
function Block({title,help:desc,children}){return <div className="block"><div className="blockHead"><h2>{title}</h2>{desc&&<p>{desc}</p>}</div>{children}</div>}
export default function Page(){
 const [lang,setLang]=useState('Mandarin'),[voice,setVoice]=useState('Male'),[genre,setGenre]=useState(O.genre[0]),[bpm,setBpm]=useState(108),[groove,setGroove]=useState(O.groove[0]);
 const [mood,setMood]=useState(['Melancholic','Yearning','Cathartic']),[tone,setTone]=useState(['Warm','Dark','Husky']),[tech,setTech]=useState(['Conversational phrasing','Chest-dominant mix','Controlled rasp','Sustained upper notes','Subtle vibrato']);
 const [melody,setMelody]=useState(['Narrow conversational verse','Rising pre-chorus contour','Wide chorus range','Strong recurring hook']),[harmony,setHarmony]=useState(['Minor-key leaning','Tension-building pre-chorus']);
 const [inst,setInst]=useState(['Piano','Clean Electric Guitar','Live Drums','Bass','Cinematic Strings','Atmospheric Pads']),[prod,setProd]=useState(['Vocal-forward mix','Warm low-midrange','Spacious stereo image','Controlled plate reverb','Natural dynamics','Modern polished master']),[avoid,setAvoid]=useState(['EDM drops','Trap hi-hats','Excessive vocal runs','Constant belting','Early climax']);
 const [concept,setConcept]=useState('A love that cannot be recovered; restrained regret grows into emotional release.'),[hook,setHook]=useState(''),[custom,setCustom]=useState('');
 const [hookType,setHookType]=useState('Title-centered hook'),[hookRep,setHookRep]=useState('Strong'),[hookPlace,setHookPlace]=useState('Both opening and ending'),[reinforce,setReinforce]=useState(true);
 const [journey,setJourney]=useState({verse:['Intimate','Conversational'],pre:['Increasing tension','Rising register'],chorus:['Open and powerful','Emotional release','Chest-dominant mix'],bridge:['Pull back','Vulnerable','Tension rebuild'],final:['Maximum emotional release','Strongest projection','Added harmony layers','Selective ad-libs']});
 const [energy,setEnergy]=useState({'Verse 1':2,'Pre-Chorus':3,'Chorus 1':4,'Verse 2':3,'Chorus 2':4,'Bridge':3,'Final Chorus':5});
 const [tab,setTab]=useState('suno'),[copied,setCopied]=useState(false); const arc=sections.map(s=>`${s} ${energy[s]}/5`).join(' → '); const warnings=[];
 if(mood.length>4)warnings.push('情绪过多，建议保留 2–4 个主导情绪。'); if(tone.length>4)warnings.push('人声音色过多，可能削弱歌手一致性。'); if(inst.length>8)warnings.push('乐器密度较高，编曲清晰度可能下降。'); if(energy['Final Chorus']<=energy['Chorus 1'])warnings.push('Final Chorus 应超过 Chorus 1，才能完成情绪建筑。'); if(!melody.includes('Strong recurring hook'))warnings.push('尚未选择明确的重复旋律 Hook。');
 const score=Math.max(48,Math.min(100,98-warnings.length*7-(concept.trim().length<25?10:0)-(mood.length===0?12:0)));
 const hookEnglish=`Use a ${hookType.toLowerCase()} with ${hookRep.toLowerCase()} repetition. ${hookPlace==='Pre-Chorus tease'?'Introduce a subtle hook tease in the pre-chorus.':hookPlace==='Chorus opening'?'Place the full hook at the opening of each chorus.':hookPlace==='Chorus ending'?'Place the full hook at the ending of each chorus.':'Place the full hook at both the opening and ending of each chorus.'} ${reinforce?'Final chorus reinforces the same hook through stronger repetition, additional backing vocal layers and/or melodic lift without changing the core hook identity.':'Keep the established hook identity consistent without adding a separate late-song hook.'} Do not introduce a completely different hook late in the song.`;
 const vocalEnglish=Object.entries(journey).map(([part,values])=>`${part}: ${values.join(', ').toLowerCase()}`).join('. ')+'.';
 const section=`Verse 1 (${energy['Verse 1']}/5): restrained opening; keep the vocal intimate and the melody conversational.\nPre-Chorus (${energy['Pre-Chorus']}/5): increase unresolved tension and register without releasing fully.\nChorus 1 (${energy['Chorus 1']}/5): establish the central hook with a wider range and emotional lift.\nVerse 2 (${energy['Verse 2']}/5): retain momentum and add one new texture; do not reset to Verse 1 energy.\nChorus 2 (${energy['Chorus 2']}/5): develop the hook with stronger layering and urgency than Chorus 1.\nBridge (${energy.Bridge}/5): pull back for contrast, then rebuild tension rather than repeating the chorus.\nFinal Chorus (${energy['Final Chorus']}/5): highest controlled emotional and arrangement energy; preserve pitch, clarity and hook identity.`;
 const core=`${lang} ${genre}, ${bpm} BPM, ${groove.toLowerCase()}. ${voice} vocal with ${tone.join(', ')} tone. ${mood.join(' → ')} emotional arc. ${tech.join(', ')} delivery. ${melody.join(', ')} melody. ${harmony.join(', ')} harmony. ${inst.join(', ')} instrumentation. ${prod.join(', ')}.`;
 const lyricBrief=`Write original ${lang} lyrics about: ${concept}${hook?` Central hook concept: “${hook}”.`:''} Use concrete imagery, natural conversational language and a clear emotional point of view. Verses reveal details; the pre-chorus increases unresolved tension; the chorus states the central emotional truth in concise memorable language; the bridge adds a new realization. ${custom?`Additional direction: ${custom} `:''}Do not copy existing lyrics, melodies or a specific singer's signature delivery.`;
 const structured=`STYLE\n${core}\n\nEMOTIONAL ARC\n${mood.join(' → ')}; final chorus is the controlled peak.\n\nVOCAL DNA\nTone: ${tone.join(', ')}. Technique: ${tech.join(', ')}.\n\nVOCAL JOURNEY\n${vocalEnglish}\n\nHOOK DNA\n${hookEnglish}${hook?`\nCentral hook concept: ${hook}.`:''}\n\nMELODY\n${melody.join(', ')}.\n\nHARMONY\n${harmony.join(', ')}.\n\nARRANGEMENT ARC\n${section}\n\nSECTION ENERGY\n${arc}\n\nPRODUCTION / MIX\n${prod.join(', ')}.\n\nLYRIC DIRECTION\n${lyricBrief}\n\nAVOID\n${avoid.join(', ')}. Reference DNA describes production characteristics only. Request original melody, original lyrics and an original vocal identity.`;
 const suno=structured,udio=`Produce an original ${lang} ${genre} track at approximately ${bpm} BPM.\n\n${structured}\n\nKeep this professional production direction in English for Udio; lyrics may use ${lang}.`,full=`SONG DNA / PRODUCTION BLUEPRINT\n\n${structured}`; const outputs={suno,udio,lyrics:lyricBrief,full},output=outputs[tab];
 const setJourneyValue=part=>value=>setJourney({...journey,[part]:value});
 const preset=()=>{setGenre(O.genre[0]);setBpm(108);setGroove(O.groove[0]);setMood(['Melancholic','Yearning','Cathartic']);setTone(['Warm','Dark','Husky']);setTech(['Conversational phrasing','Chest-dominant mix','Controlled rasp','Sustained upper notes','Subtle vibrato']);setMelody(['Narrow conversational verse','Rising pre-chorus contour','Wide chorus range','Strong recurring hook']);setHarmony(['Minor-key leaning','Tension-building pre-chorus']);setInst(['Piano','Clean Electric Guitar','Live Drums','Bass','Cinematic Strings','Atmospheric Pads']);setEnergy({'Verse 1':2,'Pre-Chorus':3,'Chorus 1':4,'Verse 2':3,'Chorus 2':4,'Bridge':3,'Final Chorus':5});setHookType('Title-centered hook');setHookRep('Strong');setHookPlace('Both opening and ending');setReinforce(true);setJourney({verse:['Intimate','Conversational'],pre:['Increasing tension','Rising register'],chorus:['Open and powerful','Emotional release','Chest-dominant mix'],bridge:['Pull back','Vulnerable','Tension rebuild'],final:['Maximum emotional release','Strongest projection','Added harmony layers','Selective ad-libs']});};
 const copy=async()=>{await navigator.clipboard.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),1200)};
 return <main><header><div><span className="eyebrow">PRODUCTION EDITION · V4</span><h1>Song DNA Studio</h1><p>AI 音乐制作 DNA 工作室 · 先设计歌曲的制作 DNA，再生成可直接用于 AI 音乐平台的专业 Prompt。</p><span className="subtitle">中文制作界面 · Professional Prompt Engine</span></div><div className="score"><b>{score}</b><span>Prompt 完整度</span></div></header>
 <div className="preset"><div><b>参考灵感的情绪推进</b><span>克制主歌 → 张力上升 → 强力副歌 → 最大化 Final Chorus</span></div><button onClick={preset}>载入示范 DNA</button></div><div className="grid"><section className="panel">
 <Block title="1 · 基础设定" help="先确定歌曲的制作框架，再逐步增加细节。"><div className="row"><label>歌曲语言<select value={lang} onChange={e=>setLang(e.target.value)}>{['Mandarin','English','Malay','Cantonese'].map(x=><option key={x}>{x}</option>)}</select></label><label>主唱<select value={voice} onChange={e=>setVoice(e.target.value)}>{['Male','Female','Duet'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>主要曲风<select value={genre} onChange={e=>setGenre(e.target.value)}>{O.genre.map(x=><option key={x}>{x}</option>)}</select></label><div className="row"><label>速度 <strong>{bpm} BPM</strong><input type="range" min="55" max="160" value={bpm} onChange={e=>setBpm(+e.target.value)}/></label><label>节奏律动<select value={groove} onChange={e=>setGroove(e.target.value)}>{O.groove.map(x=><option key={x}>{x}</option>)}</select></label></div></Block>
 <Block title="2 · 情绪发展" help="选择 2–4 个主导情绪，并按歌曲发展顺序排列。"><Multi items={O.mood} value={mood} setValue={setMood}/></Block><Block title="3 · 人声 DNA" help="音色决定声音质感，技巧决定主唱的演绎方式。"><h3>音色 / 质感</h3><Multi items={O.tone} value={tone} setValue={setTone}/><h3>演唱 / 技巧</h3><Multi items={O.technique} value={tech} setValue={setTech}/></Block>
 <Block title="4 · 旋律与和声" help="控制旋律走向，以及张力在哪里累积。"><h3>旋律行为</h3><Multi items={O.melody} value={melody} setValue={setMelody}/><h3>和声方向</h3><Multi items={O.harmony} value={harmony} setValue={setHarmony}/></Block>
 <Block title="5 · Hook DNA · 副歌记忆点设计" help="控制核心 Hook 的记忆性、重复性和出现位置。"><h3>Hook 类型</h3><Choice items={hookTypes} value={hookType} setValue={setHookType}/><h3>Hook 重复程度</h3><Choice items={hookRepetition} value={hookRep} setValue={setHookRep}/><h3>Hook 出现位置</h3><Choice items={hookPlacement} value={hookPlace} setValue={setHookPlace}/><label className="switch"><input type="checkbox" checked={reinforce} onChange={e=>setReinforce(e.target.checked)}/><span>Final Chorus Hook Reinforcement</span><small>{reinforce?'开启：用更强重复、和声层或旋律抬升强化既有 Hook。':'关闭：保持既有 Hook，不加入后段强化。'}</small></label></Block>
 <Block title="6 · Vocal Journey · 人声情绪旅程" help="描述主唱从 Verse 到 Final Chorus 如何逐步改变表达。">{Object.entries(journeyOptions).map(([part,items])=><div key={part}><h3>{({verse:'Verse Vocal · 主歌人声',pre:'Pre-Chorus Vocal · 预副歌人声',chorus:'Chorus Vocal · 副歌人声',bridge:'Bridge Vocal · Bridge 人声',final:'Final Chorus Vocal · 最终副歌人声'})[part]}</h3><Choice items={items} value={journey[part]} setValue={setJourneyValue(part)} multiple/></div>)}</Block>
 <Block title="7 · 编曲" help="选择乐器；段落能量会决定它们何时扩展。"><Multi items={O.instruments} value={inst} setValue={setInst}/></Block><Block title="8 · 段落能量" help="1 = 裸露 / 极简，5 = 最大强度。Final Chorus 通常应达到全曲最高受控能量。"><div className="energy">{sections.map(s=><label key={s}><span>{s}<b>{energy[s]}/5</b></span><input type="range" min="1" max="5" value={energy[s]} onChange={e=>setEnergy({...energy,[s]:+e.target.value})}/></label>)}</div></Block><Block title="9 · 制作与混音"><Multi items={O.production} value={prod} setValue={setProd}/></Block>
 <Block title="10 · 歌曲故事" help="用自然语言描述谁、发生了什么，以及人物最后发生了什么改变。"><label>歌曲概念<textarea value={concept} onChange={e=>setConcept(e.target.value)} rows="4"/></label><label>Hook 句子 / 核心想法（可选）<input value={hook} onChange={e=>setHook(e.target.value)} placeholder="例如：太晚才学会放手"/></label><label>补充方向<textarea value={custom} onChange={e=>setCustom(e.target.value)} rows="3" placeholder="意象、视角、结尾、特殊要求……"/></label></Block><Block title="11 · 避免元素" help="预防常见的生成失败，保持制作方向清晰。"><Multi items={O.avoid} value={avoid} setValue={setAvoid}/></Block>
 </section><aside className="panel sticky"><span className="eyebrow">实时制作输出</span><h2>歌曲 DNA</h2><div className="dna"><b>{lang} · {genre}</b><span>{bpm} BPM · {groove} · {voice}</span><span>{mood.join(' → ')||'尚未选择情绪'}</span><span>{tone.join(' / ')||'尚未选择人声音色'}</span></div>{warnings.length>0?<div className="warn"><b>制作检查</b>{warnings.map(w=><span key={w}>⚠ {w}</span>)}</div>:<div className="pass">✓ DNA 结构协调</div>}<div className="tabs"><button className={tab==='suno'?'active':''} onClick={()=>setTab('suno')}>Suno</button><button className={tab==='udio'?'active':''} onClick={()=>setTab('udio')}>Udio</button><button className={tab==='lyrics'?'active':''} onClick={()=>setTab('lyrics')}>Lyrics</button><button className={tab==='full'?'active':''} onClick={()=>setTab('full')}>Master</button></div><div className="output">{output}</div><button className="copy" onClick={copy}>{copied?'已复制 ✓':`复制 ${tab==='suno'?'Suno Prompt':tab==='udio'?'Udio Prompt':tab==='lyrics'?'Lyrics':'Master'}`}</button><p className="tip">参考歌曲只用于分析制作特征，例如情绪发展、编曲密度、人声动态、Hook 结构与混音方向。不要复制原曲旋律、歌词或歌手的标志性演唱方式。</p></aside></div></main>
}
