'use client';
import {useMemo,useState} from 'react';
const O={
 genre:['Mandarin Emotional Pop-Rock','Mandarin Pop Ballad','Cinematic Pop','Adult Contemporary','R&B Pop','Indie Pop','Folk Pop','Soft Rock'],
 mood:['Melancholic','Yearning','Regretful','Nostalgic','Bittersweet','Hopeful','Lonely','Restrained','Desperate','Cathartic'],
 tone:['Warm','Dark','Deep','Husky','Raspy','Breathy','Clean','Gritty','Smoky','Resonant'],
 technique:['Conversational phrasing','Chest-dominant mix','Controlled rasp','Sustained upper notes','Subtle vibrato','Falsetto contrast','Soft onset','Powerful belt'],
 groove:['Steady 4/4','Half-time emotional groove','Driving live-rock groove','Sparse ballad pulse','Syncopated pop groove'],
 melody:['Narrow conversational verse','Rising pre-chorus contour','Wide chorus range','Strong recurring hook','Long sustained chorus notes','Simple memorable motif','Call-and-response phrases'],
 harmony:['Minor-key leaning','Bittersweet major/minor mixture','Simple diatonic harmony','Tension-building pre-chorus','Emotional suspended chords','Dramatic borrowed chords'],
 instruments:['Piano','Acoustic Guitar','Clean Electric Guitar','Distorted Electric Guitar','Live Drums','Bass','Cinematic Strings','Atmospheric Pads','Backing Vocals','Percussion'],
 production:['Vocal-forward mix','Warm low-midrange','Spacious stereo image','Controlled plate reverb','Short vocal delay','Natural dynamics','Organic live feel','Modern polished master'],
 avoid:['EDM drops','Trap hi-hats','Excessive vocal runs','Constant belting','Bright synth leads','Overly theatrical singing','Over-compression','Busy arrangement','Early climax']
};
const sections=['Verse 1','Pre-Chorus','Chorus','Verse 2','Chorus 2','Bridge','Final Chorus'];
const help={Warm:'Rounded, full tone with softer high frequencies.',Dark:'Lower, weightier tone with less brightness.',Husky:'Breathy roughness; intimate and mature.',Raspy:'More audible rough edge than husky.',Gritty:'Controlled distortion for emotional intensity.',Breathy:'More air in the tone; intimate, fragile feel.','Chest-dominant mix':'Strong upper register that keeps chest weight without pure shouting.','Controlled rasp':'Add texture mainly at emotional peaks, not constantly.','Sustained upper notes':'Hold important chorus notes to create lift.','Conversational phrasing':'Natural speech-like rhythm in verses.'};
function Multi({items,value,setValue,max=99}){return <div className="chips">{items.map(x=><button type="button" title={help[x]||''} key={x} className={value.includes(x)?'on':''} onClick={()=>setValue(value.includes(x)?value.filter(v=>v!==x):(value.length<max?[...value,x]:value))}>{x}{help[x]&&<small>ⓘ</small>}</button>)}</div>}
function Block({title,help:desc,children}){return <div className="block"><div className="blockHead"><h2>{title}</h2>{desc&&<p>{desc}</p>}</div>{children}</div>}
export default function Page(){
 const [lang,setLang]=useState('Mandarin'),[voice,setVoice]=useState('Male'),[genre,setGenre]=useState(O.genre[0]),[bpm,setBpm]=useState(108),[groove,setGroove]=useState(O.groove[0]);
 const [mood,setMood]=useState(['Melancholic','Yearning','Cathartic']),[tone,setTone]=useState(['Warm','Dark','Husky']),[tech,setTech]=useState(['Conversational phrasing','Chest-dominant mix','Controlled rasp','Sustained upper notes','Subtle vibrato']);
 const [melody,setMelody]=useState(['Narrow conversational verse','Rising pre-chorus contour','Wide chorus range','Strong recurring hook']),[harmony,setHarmony]=useState(['Minor-key leaning','Tension-building pre-chorus']);
 const [inst,setInst]=useState(['Piano','Clean Electric Guitar','Live Drums','Bass','Cinematic Strings','Atmospheric Pads']),[prod,setProd]=useState(['Vocal-forward mix','Warm low-midrange','Spacious stereo image','Controlled plate reverb','Natural dynamics','Modern polished master']),[avoid,setAvoid]=useState(['EDM drops','Trap hi-hats','Excessive vocal runs','Constant belting','Early climax']);
 const [concept,setConcept]=useState('A love that cannot be recovered; restrained regret grows into emotional release.'),[hook,setHook]=useState(''),[custom,setCustom]=useState('');
 const [energy,setEnergy]=useState({'Verse 1':2,'Pre-Chorus':3,'Chorus':4,'Verse 2':3,'Chorus 2':4,'Bridge':3,'Final Chorus':5});
 const [tab,setTab]=useState('suno'),[copied,setCopied]=useState(false);
 const arc=sections.map(s=>`${s} ${energy[s]}/5`).join(' → ');
 const warnings=[];
 if(mood.length>4)warnings.push('Too many moods: keep 2–4 dominant emotions.');
 if(tone.length>4)warnings.push('Too many vocal textures may make the singer inconsistent.');
 if(inst.length>8)warnings.push('Instrument palette is dense; arrangement clarity may drop.');
 if(energy['Final Chorus']<=energy['Chorus'])warnings.push('Final chorus should exceed the first chorus for this build architecture.');
 if(!melody.includes('Strong recurring hook'))warnings.push('No explicit recurring melodic hook is selected.');
 if(tech.includes('Powerful belt')&&avoid.includes('Constant belting'))warnings.push('Use belting only at selected peaks; avoid constant belting.');
 if(tone.includes('Breathy')&&tone.includes('Gritty'))warnings.push('Breathy + gritty can work, but assign them to different sections for consistency.');
 const score=Math.max(48,Math.min(100,98-warnings.length*7-(concept.trim().length<25?10:0)-(mood.length===0?12:0)));
 const section=`Verse 1 (${energy['Verse 1']}/5): intimate and restrained; narrow conversational melody; sparse piano/guitar texture; vocal close and controlled.\nPre-Chorus (${energy['Pre-Chorus']}/5): melody rises; harmonic tension increases; bass and strings begin to lift; do not fully release yet.\nChorus (${energy['Chorus']}/5): wider range; one clear recurring hook; stronger chest-dominant mix; full live rhythm section; emotional lift without uncontrolled shouting.\nVerse 2 (${energy['Verse 2']}/5): retain momentum and add one new texture; do not reset to the opening.\nChorus 2 (${energy['Chorus 2']}/5): stronger layering and vocal urgency than Chorus 1.\nBridge (${energy['Bridge']}/5): selectively pull back drums/instruments; expose vocal; create contrast and tension.\nFinal Chorus (${energy['Final Chorus']}/5): largest vocal and arrangement moment; add backing layers/strings; maximum cathartic release while preserving pitch and control.`;
 const core=`${lang} ${genre}, ${bpm} BPM, ${groove.toLowerCase()}. ${voice} vocal with ${tone.join(', ')} tone. Emotional arc: ${mood.join(' → ')}. Vocal delivery: ${tech.join(', ')}. Melody: ${melody.join(', ')}. Harmony: ${harmony.join(', ')}. Instruments: ${inst.join(', ')}. Production: ${prod.join(', ')}. Energy: ${arc}. Avoid: ${avoid.join(', ')}.`;
 const lyricBrief=`Write an original ${lang} song about: ${concept}${hook?` Central hook concept: “${hook}”.`:''} Use concrete imagery, natural conversational language and a clear emotional point of view. Verses should reveal details rather than summarize feelings. Pre-chorus should increase unresolved tension. Chorus should state the central emotional truth in concise memorable language. Bridge must add a new realization rather than repeat the chorus.${custom?` Additional direction: ${custom}`:''} Do not copy existing lyrics, melodies or a specific singer's signature delivery.`;
 const suno=`STYLE\n${core}\n\nARRANGEMENT ARC\n${section}\n\nLYRIC DIRECTION\n${lyricBrief}`;
 const udio=`Create an original ${lang} ${genre} track at approximately ${bpm} BPM with ${groove.toLowerCase()}. Prioritize a coherent mature ${voice.toLowerCase()} performance: ${tone.join(', ').toLowerCase()}, using ${tech.join(', ').toLowerCase()}. The emotional progression is ${mood.join(' → ').toLowerCase()}. Use ${inst.join(', ').toLowerCase()}, with ${prod.join(', ').toLowerCase()}.\n\nComposition: ${melody.join(', ').toLowerCase()}; ${harmony.join(', ').toLowerCase()}.\n\n${section}\n\nSong concept: ${concept}${hook?` Hook concept: ${hook}.`:''}${custom?` ${custom}`:''}\n\nAvoid ${avoid.join(', ').toLowerCase()}. Keep the composition, lyrics and vocal identity original.`;
 const full=`SONG DNA / PRODUCTION BRIEF\n${core}\n\nSECTION-BY-SECTION DIRECTION\n${section}\n\nLYRICS BRIEF\n${lyricBrief}`;
 const outputs={suno,udio,lyrics:lyricBrief,full}; const output=outputs[tab];
 const preset=()=>{setGenre(O.genre[0]);setBpm(108);setGroove(O.groove[0]);setMood(['Melancholic','Yearning','Cathartic']);setTone(['Warm','Dark','Husky']);setTech(['Conversational phrasing','Chest-dominant mix','Controlled rasp','Sustained upper notes','Subtle vibrato']);setMelody(['Narrow conversational verse','Rising pre-chorus contour','Wide chorus range','Strong recurring hook']);setHarmony(['Minor-key leaning','Tension-building pre-chorus']);setInst(['Piano','Clean Electric Guitar','Live Drums','Bass','Cinematic Strings','Atmospheric Pads']);setEnergy({'Verse 1':2,'Pre-Chorus':3,'Chorus':4,'Verse 2':3,'Chorus 2':4,'Bridge':3,'Final Chorus':5});};
 const copy=async()=>{await navigator.clipboard.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),1200)};
 return <main><header><div><span className="eyebrow">PRODUCTION EDITION · V3</span><h1>Song DNA Studio</h1><p>Design the production DNA first. Then generate a platform-ready prompt.</p></div><div className="score"><b>{score}</b><span>Prompt Clarity</span></div></header>
 <div className="preset"><div><b>Reference-inspired emotional build</b><span>Restrained verse → rising tension → powerful chorus → largest final chorus</span></div><button onClick={preset}>Load Starter DNA</button></div>
 <div className="grid"><section className="panel">
 <Block title="1 · Foundation" help="Set the musical frame before adding detail."><div className="row"><label>Language<select value={lang} onChange={e=>setLang(e.target.value)}>{['Mandarin','English','Malay','Cantonese'].map(x=><option key={x}>{x}</option>)}</select></label><label>Voice<select value={voice} onChange={e=>setVoice(e.target.value)}>{['Male','Female','Duet'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Primary style<select value={genre} onChange={e=>setGenre(e.target.value)}>{O.genre.map(x=><option key={x}>{x}</option>)}</select></label><div className="row"><label>Tempo <strong>{bpm} BPM</strong><input type="range" min="55" max="160" value={bpm} onChange={e=>setBpm(+e.target.value)}/></label><label>Groove<select value={groove} onChange={e=>setGroove(e.target.value)}>{O.groove.map(x=><option key={x}>{x}</option>)}</select></label></div></Block>
 <Block title="2 · Emotional Arc" help="Choose 2–4 dominant emotions. Order matters: beginning → ending."><Multi items={O.mood} value={mood} setValue={setMood}/></Block>
 <Block title="3 · Vocal DNA" help="Tone = voice texture. Technique = how the singer performs."><h3>Tone / texture</h3><Multi items={O.tone} value={tone} setValue={setTone}/><h3>Delivery / technique</h3><Multi items={O.technique} value={tech} setValue={setTech}/></Block>
 <Block title="4 · Melody & Harmony" help="Control how the melody moves and where tension is created."><h3>Melody behavior</h3><Multi items={O.melody} value={melody} setValue={setMelody}/><h3>Harmony</h3><Multi items={O.harmony} value={harmony} setValue={setHarmony}/></Block>
 <Block title="5 · Arrangement Palette" help="Choose instruments; the section engine controls when intensity expands."><Multi items={O.instruments} value={inst} setValue={setInst}/></Block>
 <Block title="6 · Section Energy" help="1 = exposed/minimal · 5 = maximum intensity."><div className="energy">{sections.map(s=><label key={s}><span>{s}<b>{energy[s]}/5</b></span><input type="range" min="1" max="5" value={energy[s]} onChange={e=>setEnergy({...energy,[s]:+e.target.value})}/></label>)}</div></Block>
 <Block title="7 · Production & Mix"><Multi items={O.production} value={prod} setValue={setProd}/></Block>
 <Block title="8 · Song Story" help="Normal language is fine. Be specific about who, what happened, and what changed."><label>Song concept<textarea value={concept} onChange={e=>setConcept(e.target.value)} rows="4"/></label><label>Hook phrase / central idea (optional)<input value={hook} onChange={e=>setHook(e.target.value)} placeholder="e.g. I learned to let you go too late"/></label><label>Additional direction<textarea value={custom} onChange={e=>setCustom(e.target.value)} rows="3" placeholder="Imagery, perspective, ending, special instruction..."/></label></Block>
 <Block title="9 · Negative Direction" help="Prevent common generation failures."><Multi items={O.avoid} value={avoid} setValue={setAvoid}/></Block>
 </section><aside className="panel sticky"><span className="eyebrow">LIVE PRODUCTION OUTPUT</span><h2>Song DNA</h2><div className="dna"><b>{lang} · {genre}</b><span>{bpm} BPM · {groove} · {voice}</span><span>{mood.join(' → ')||'No mood selected'}</span><span>{tone.join(' / ')||'No vocal texture selected'}</span></div>{warnings.length>0?<div className="warn"><b>Production checks</b>{warnings.map(w=><span key={w}>⚠ {w}</span>)}</div>:<div className="pass">✓ DNA is internally coherent</div>}<div className="tabs"><button className={tab==='suno'?'active':''} onClick={()=>setTab('suno')}>Suno</button><button className={tab==='udio'?'active':''} onClick={()=>setTab('udio')}>Udio</button><button className={tab==='lyrics'?'active':''} onClick={()=>setTab('lyrics')}>Lyrics</button><button className={tab==='full'?'active':''} onClick={()=>setTab('full')}>Master</button></div><div className="output">{output}</div><button className="copy" onClick={copy}>{copied?'Copied ✓':`Copy ${tab==='suno'?'Suno Prompt':tab==='udio'?'Udio Prompt':tab==='lyrics'?'Lyrics Brief':'Master Prompt'}`}</button><p className="tip">Reference DNA describes production characteristics only. Keep melody, lyrics and vocal identity original.</p></aside></div></main>}
